on:
  workflow_call:

jobs:
  #Deploy's job
  deploy:
    #Depends on build's job
    # needs: build
    # if: ${{ contains(github.event.*.labels.*.name, 'deploy') }}
    name: Deploy
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v2
        with:
          name: artifact