name: CI Pipeline - Main Workflow
on:
  #Trigger the workflow on push from the develop branch
  # label:
  #   types:
  #     - on-going work
  #     - test-only
  #     - sca-only
  #     - scan-only
  #     - test-only
  #     - buid-only
  push:
    branches:
      - feature-*
      - master
      - develop
    issues:
      types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  call-sonar-workflow:
    uses: BLOCK-AID/github-actions-template/.github/workflows/sonar.yml

  call-trivy-workflow:
    uses: BLOCK-AID/github-actions-template/.github/workflows/trivy.yml

  call-test-workflow:
    uses: BLOCK-AID/github-actions-template/.github/workflows/test.yml

  call-build-workflow:
    uses: BLOCK-AID/github-actions-template/.github/workflows/build.yml

  call-deploy-workflow:
    uses: BLOCK-AID/github-actions-template/.github/workflows/deploy.yml