name: CI Pipeline - Main Workflow
on:

  #Trigger the workflow on push from the develop branch
  # label:
  #   types:
  #     - on-going work
  #     - test-only
  #     - sca-only
  #     - scan-only
  #     - test-only
  #     - buid-only
  push:
    branches:
      - 'feature-*'
      - master
      - develop
    # issues:
    #   types: [synchronize, opened, reopened, labeled, unlabeled]

  # label:
  #   types: [created, edited]

env:
  WF_LABEL: Avail to all jobs
  
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV Variables
        run: |
          echo "WF_ENV: ${WF_ENV}"

  dump-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump CitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_CONTEXT.event.commits.message"

  dump-job-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

  call-sonar-workflow:
    if: github.event.label.name == 'sca-only'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was sca-only'

    # uses: BLOCK-AID/github-actions-template/.github/workflows/sonar.yml@feature-1
    # secrets:
    #   host: ${{ secrets.SONARQUBE_HOST }}
    #   login: ${{ secrets.SONARQUBE_TOKEN }}

  call-trivy-workflow:
    if: github.event.label.name == 'sast-only'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was sast-only'

    # uses: BLOCK-AID/github-actions-template/.github/workflows/trivy.yml@feature-1

  call-test-workflow:
    if: github.event.label.name == 'test-only'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was test-only'
    # uses: BLOCK-AID/github-actions-template/.github/workflows/test.yml@feature-1

  call-build-workflow:
    if: github.event.label.name == 'build-only'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was build-only'
    # uses: BLOCK-AID/github-actions-template/.github/workflows/build.yml@feature-1

  call-deploy-workflow:
    if: github.event.label.name == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was deploy'
    needs: call-build-workflow
    # uses: BLOCK-AID/github-actions-template/.github/workflows/deploy.yml@feature-1

