name: CI Pipeline - Main Workflow
on:
  #Trigger the workflow on push from the develop branch
  push:
    branches:
      - 'feature-*'
      - master
      - develop

env:
  WF_MESSAGE: ${{ github.event.head_commit.message }}  #get message from commit
  
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV Variables
        run: |
          echo "WF_MESSAGE: ${WF_MESSAGE}"

  # dump-github-context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump CitHub Context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: |
  #         echo "$GITHUB_CONTEXT"

  # dump-job-context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump Job Context
  #       env:
  #         JOB_CONTEXT: ${{ toJson(job) }}
  #       run: echo "$JOB_CONTEXT"

  call-sonar-workflow:
    if: "contains(github.event.head_commit.message, 'sca-only')"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was sca-only'

    # uses: BLOCK-AID/github-actions-template/.github/workflows/sonar.yml@feature-1
    # secrets:
    #   host: ${{ secrets.SONARQUBE_HOST }}
    #   login: ${{ secrets.SONARQUBE_TOKEN }}

  call-scan-workflow:
    if: "contains(github.event.head_commit.message, 'sast-only')"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was sast-only'

    # uses: BLOCK-AID/github-actions-template/.github/workflows/trivy.yml@feature-1

  call-test-workflow:
    if: "contains(github.event.head_commit.message, 'test-only')"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was test-only'
    # uses: BLOCK-AID/github-actions-template/.github/workflows/test.yml@feature-1

  call-build-workflow:
    if: "contains(github.event.head_commit.message, 'build-only')"
    needs: [call-sonar-workflow, call-scan-workflow, call-test-workflow]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was build-only'
    # uses: BLOCK-AID/github-actions-template/.github/workflows/build.yml@feature-1

  call-deploy-workflow:
    if: "contains(github.event.head_commit.message, 'deploy')"
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The label was deploy'
    
    # uses: BLOCK-AID/github-actions-template/.github/workflows/deploy.yml@feature-1

