name: CI Pipeline - Develop Branch Workflow
on:
  #Trigger the workflow on push to the feature branch
  push:
    branches:
      - develop
      - 'bugfix-*'

env:
  WF_MESSAGE: ${{ github.event.head_commit.message }}  #get message from commit
  
jobs:
  # Jobs are controlled by the commit message flags in [...], they are:
  # skip-actions  : run no jobs
  # all-jobs  : run all jobs
  # sca-only  : run SonarQube only
  # scan-only : run SAST scans only
  # test-only : run unit tests
  # build-only : build binary / image
  # deploy    : deploy application locally (stand alone jave, docker, or kubernetes)
  # merge  : raise Pull Request to merge feature to master branch and tag

  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV Variables
        run: |
          echo "WF_MESSAGE: ${WF_MESSAGE}"

  call-sonar-workflow:
    if: "contains(github.event.head_commit.message, 'sca-only') || contains(github.event.head_commit.message, 'all-jobs')" 
    needs: log-env
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo 'Running sca-only'
    uses: BLOCK-AID/ci_workflows/.github/workflows/sonar.yml@master
    secrets:
      host: ${{ secrets.SONARQUBE_HOST }}
      login: ${{ secrets.SONARQUBE_TOKEN }}

  call-scan-workflow:
    if: "contains(github.event.head_commit.message, 'sast-only') || contains(github.event.head_commit.message, 'all-jobs')" 
    needs: log-env
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo 'Running sast-only'
    uses: BLOCK-AID/ci_workflows/.github/workflows/trivy.yml@master

  call-test-workflow:
    if: "contains(github.event.head_commit.message, 'test-only') || contains(github.event.head_commit.message, 'all-jobs')" 
    needs: log-env
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo 'Running test-only'
    uses: BLOCK-AID/ci_workflows/.github/workflows/test.yml@master

  call-build-workflow:
    if: "contains(github.event.head_commit.message, 'build-only') || contains(github.event.head_commit.message, 'all-jobs')" 
    needs: [call-sonar-workflow, call-scan-workflow, call-test-workflow]
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo 'Running build-only'
    uses: BLOCK-AID/ci_workflows/.github/workflows/build.yml@master

  call-deploy-workflow:
    if: "contains(github.event.head_commit.message, 'deploy') || contains(github.event.head_commit.message, 'all-jobs')" 
    needs: call-build-workflow
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo 'Running local deploy'
    uses: BLOCK-AID/ci_workflows/.github/workflows/deploy.yml@master

  call-raisepr-workflow:
    if: "contains(github.event.head_commit.message, 'raise-pr') || contains(github.event.head_commit.message, 'all-jobs')" 
    # needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Raising - Updating PR to merge feature branch to develop branch'
    # uses: BLOCK-AID/ci_workflows/.github/workflows/deploy.yml@master

