name: CI Pipeline - Feature Branch Workflow
on:
  #Trigger the workflow on PR from feature branch to develop branch
  pull_request:
    types: 
      - synchronize
    branches:
      - develop

env:
  WF_MESSAGE: ${{ github.event.head_commit.message }}  #get message from commit
  WF_ACTION: ${{ github.event.head_commit.message }}  #get message from commit
  
jobs:
  # Jobs are controlled by the PR labels , they are:
  # skip-actions  : run no jobs
  # all-jobs  : run all jobs
  # sca-only  : run SonarQube only
  # scan-only : run SAST scans only
  # test-only : run unit tests
  # build-only : build binary / image
  # deploy    : deploy application locally (stand alone jave, docker, or kubernetes)
  # merge  : raise Pull Request to merge feature to develop branch
  # raise-pr  : raise Pull Request to move feature to develop branch
  #

  dump-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_ACTION: ${{ github.event.action }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo ${{ env.JOB_ACTION }}
          echo ${{ env.PR_NUMBER }}
          echo ${{ env.GITHUB_CONTEXT }}

  dump-job-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo ${{ env.JOB_CONTEXT }}

  log-env:
    needs: [dump-github-context, dump-job-context]
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV Variables
        run: |
          echo "WF_MESSAGE: ${WF_MESSAGE}"

  call-sca-workflow:
    if: "contains(github.event.pull_request.labels.*.name, 'sca-only') || contains(github.event.pull_request.labels.*.name, 'all-jobs')" 
    needs: log-env
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running sca-only'
    # uses: BLOCK-AID/ci_workflows/.github/workflows/sca.yml@master
    # secrets:
    #   host: ${{ secrets.SONARQUBE_HOST }}
    #   login: ${{ secrets.SONARQUBE_TOKEN }}

  call-sast-workflow:
    # //if: "contains(github.event.pull_request.labels.name, 'sast-only') || contains(github.event.head_commit.message, 'all-jobs')" 
    if: "contains(github.event.pull_request.labels.*.name, 'sast-only') || contains(github.event.pull_request.labels.*.name, 'all-jobs')" 
    needs: log-env
    runs-on: ubuntu-latest
    steps:
      - run: 
          echo ${{github.event.head_commit.message}}
    # uses: BLOCK-AID/ci_workflows/.github/workflows/sast.yml@master

  call-test-workflow:
    if: "contains(github.event.pull_request.labels.*.name, 'test-only') || contains(github.event.pull_request.labels.*.name, 'all-jobs')" 
    needs: log-env
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running test-only'
    # uses: BLOCK-AID/ci_workflows/.github/workflows/test.yml@master

  call-build-workflow:
    if: "contains(github.event.pull_request.labels.*.name, 'build-only') || contains(github.event.pull_request.labels.*.name, 'all-jobs')" 
    needs: [call-sca-workflow, call-sast-workflow, call-test-workflow]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running build-only'
    # uses: BLOCK-AID/ci_workflows/.github/workflows/build.yml@master

  call-deploy-workflow:
    if: "contains(github.event.pull_request.labels.*.name, 'deploy') || contains(github.event.pull_request.labels.*.name, 'all-jobs')" 
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Running local deploy'
    # uses: BLOCK-AID/ci_workflows/.github/workflows/deploy.yml@master

  call-raisepr-workflow:
    if: "contains(github.event.pull_request.labels.*.name, 'raise-pr') || contains(github.event.pull_request.labels.*.name, 'all-jobs')" 
    # needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Raising - Updating PR with label to merge feature branch to develop branch'
    # uses: BLOCK-AID/ci_workflows/.github/workflows/deploy.yml@master

