name: CI Pipeline - SAST
on:
  workflow_call:

  trivy:
  #Depends on sonar's job
  #needs: sonar
  if: ${{ contains(github.event.*.labels.*.name, 'sast-only') }}
  name: Trivy Check
  runs-on: ubuntu-18.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'